version: "3.8"

services:
  db:
    build:
      context: ./db/procrastdb
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: supersecret
  userdb:
    build:
      context: ./db/userdb
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: supersecret
  api:
    build: .
    depends_on:
      - db
      - userdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
      PROCRASTDB_HOST: db
      PROCRASTDB_PORT: 5432
      USERDB_HOST: userdb
      USERDB_PORT: 5432
      JWT_SECRET: supersecretjwt
    ports:
      - 8080:8080
    restart: always
